(() => {
  const form = document.getElementById('deliveryForm');
  const nameInput = document.getElementById('receiverName');
  const phoneInput = document.getElementById('receiverPhone');
  const digitCount = document.getElementById('deliveryDigitCount');
  const signatureButtons = [...document.querySelectorAll('.signature-options button')];
  const parcelButtons = [...document.querySelectorAll('.parcel-options button')];
  const reviewLayer = document.getElementById('reviewLayer');
  const successLayer = document.getElementById('successLayer');
  const autoReturnSeconds = document.getElementById('autoReturnSeconds');
  let signature = '需要本人簽收';
  let parcel = '一般貨品';
  const goHome = () => { window.location.href = 'homepage-ui.html'; };
  let idleTimer;
  let idleDeadline;
  const resetIdle = () => { clearTimeout(idleTimer); idleDeadline=Date.now()+10000; idleTimer=setTimeout(goHome,10000); autoReturnSeconds.textContent='10'; };
  ['pointerdown','touchstart','keydown','input'].forEach(name => window.addEventListener(name,resetIdle,{passive:true}));
  setInterval(() => { autoReturnSeconds.textContent=String(Math.max(0,Math.ceil((idleDeadline-Date.now())/1000))); },250);
  resetIdle();
  const updateTime=()=>document.getElementById('headerTime').textContent=new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false});updateTime();setInterval(updateTime,30000);
  const choose=(buttons,button)=>buttons.forEach(item=>item.classList.toggle('selected',item===button));
  signatureButtons.forEach(button=>button.addEventListener('click',()=>{signature=button.dataset.value;choose(signatureButtons,button);}));
  parcelButtons.forEach(button=>button.addEventListener('click',()=>{parcel=button.dataset.value;choose(parcelButtons,button);}));
  const clearError=input=>{const field=input.closest('.delivery-field');field.classList.remove('invalid');field.querySelector('small').textContent='';};
  nameInput.addEventListener('input',()=>clearError(nameInput));
  phoneInput.addEventListener('input',()=>{phoneInput.value=phoneInput.value.replace(/\D/g,'').slice(0,10);digitCount.textContent=`${phoneInput.value.length} / 10`;clearError(phoneInput);});
  const validate=(input,message,test)=>{const field=input.closest('.delivery-field');const valid=test(input.value);field.classList.toggle('invalid',!valid);field.querySelector('small').textContent=valid?'':message;return valid;};
  document.getElementById('clearButton').addEventListener('click',()=>{form.reset();signature='需要本人簽收';parcel='一般貨品';choose(signatureButtons,signatureButtons[0]);choose(parcelButtons,parcelButtons[1]);digitCount.textContent='0 / 10';});
  form.addEventListener('submit',event=>{event.preventDefault();const a=validate(nameInput,'請輸入收件人姓名',v=>v.trim().length>0);const b=validate(phoneInput,'手機號碼須為 09 開頭的 10 碼數字',v=>/^09\d{8}$/.test(v));if(!(a&&b))return;document.getElementById('reviewName').textContent=nameInput.value.trim();document.getElementById('reviewPhone').textContent=phoneInput.value;document.getElementById('reviewSignature').textContent=signature;document.getElementById('reviewParcel').textContent=parcel;reviewLayer.classList.add('open');reviewLayer.setAttribute('aria-hidden','false');});
  document.getElementById('reviewEdit').addEventListener('click',()=>{reviewLayer.classList.remove('open');reviewLayer.setAttribute('aria-hidden','true');});
  document.getElementById('reviewSubmit').addEventListener('click',()=>{reviewLayer.classList.remove('open');successLayer.classList.add('open');document.getElementById('successName').textContent=nameInput.value.trim();});
  document.getElementById('backButton').addEventListener('click',goHome);document.getElementById('successBack').addEventListener('click',goHome);
})();
